export default {
  january: "0",
  february: "1",
  march: "2",
  april: "3",
  may: "4",
  june: "5",
  july: "6",
  august: "7",
  september: "8",
  october: "9",
  november: "10",
  december: "11",
  January: "0",
  February: "1",
  March: "2",
  April: "3",
  May: "4",
  June: "5",
  July: "6",
  August: "7",
  September: "8",
  October: "9",
  November: "10",
  December: "11",
};
